//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: snakes.proto

package me.ippolitov.fit.snakes;

@kotlin.jvm.JvmName("-initializegamePlayers")
public inline fun gamePlayers(block: me.ippolitov.fit.snakes.GamePlayersKt.Dsl.() -> kotlin.Unit): me.ippolitov.fit.snakes.SnakesProto.GamePlayers =
  me.ippolitov.fit.snakes.GamePlayersKt.Dsl._create(me.ippolitov.fit.snakes.SnakesProto.GamePlayers.newBuilder()).apply { block() }._build()
public object GamePlayersKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: me.ippolitov.fit.snakes.SnakesProto.GamePlayers.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: me.ippolitov.fit.snakes.SnakesProto.GamePlayers.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): me.ippolitov.fit.snakes.SnakesProto.GamePlayers = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class PlayersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     */
     public val players: com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.getPlayersList()
      )
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     * @param value The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addPlayers")
    public fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.add(value: me.ippolitov.fit.snakes.SnakesProto.GamePlayer) {
      _builder.addPlayers(value)
    }
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     * @param value The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignPlayers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.plusAssign(value: me.ippolitov.fit.snakes.SnakesProto.GamePlayer) {
      add(value)
    }
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     * @param values The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllPlayers")
    public fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.addAll(values: kotlin.collections.Iterable<me.ippolitov.fit.snakes.SnakesProto.GamePlayer>) {
      _builder.addAllPlayers(values)
    }
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     * @param values The players to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllPlayers")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.plusAssign(values: kotlin.collections.Iterable<me.ippolitov.fit.snakes.SnakesProto.GamePlayer>) {
      addAll(values)
    }
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     * @param index The index to set the value at.
     * @param value The players to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setPlayers")
    public operator fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.set(index: kotlin.Int, value: me.ippolitov.fit.snakes.SnakesProto.GamePlayer) {
      _builder.setPlayers(index, value)
    }
    /**
     * <pre>
     * Список всех игроков
     * </pre>
     *
     * <code>repeated .snakes.GamePlayer players = 1;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearPlayers")
    public fun com.google.protobuf.kotlin.DslList<me.ippolitov.fit.snakes.SnakesProto.GamePlayer, PlayersProxy>.clear() {
      _builder.clearPlayers()
    }

  }
}
@kotlin.jvm.JvmSynthetic
public inline fun me.ippolitov.fit.snakes.SnakesProto.GamePlayers.copy(block: me.ippolitov.fit.snakes.GamePlayersKt.Dsl.() -> kotlin.Unit): me.ippolitov.fit.snakes.SnakesProto.GamePlayers =
  me.ippolitov.fit.snakes.GamePlayersKt.Dsl._create(this.toBuilder()).apply { block() }._build()

