//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: snakes.proto

package me.ippolitov.fit.snakes;

@kotlin.jvm.JvmName("-initializegamePlayer")
public inline fun gamePlayer(block: me.ippolitov.fit.snakes.GamePlayerKt.Dsl.() -> kotlin.Unit): me.ippolitov.fit.snakes.SnakesProto.GamePlayer =
  me.ippolitov.fit.snakes.GamePlayerKt.Dsl._create(me.ippolitov.fit.snakes.SnakesProto.GamePlayer.newBuilder()).apply { block() }._build()
public object GamePlayerKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: me.ippolitov.fit.snakes.SnakesProto.GamePlayer.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: me.ippolitov.fit.snakes.SnakesProto.GamePlayer.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): me.ippolitov.fit.snakes.SnakesProto.GamePlayer = _builder.build()

    /**
     * <pre>
     * Имя игрока (для отображения в интерфейсе)
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public var name: kotlin.String
      @JvmName("getName")
      get() = _builder.getName()
      @JvmName("setName")
      set(value) {
        _builder.setName(value)
      }
    /**
     * <pre>
     * Имя игрока (для отображения в интерфейсе)
     * </pre>
     *
     * <code>required string name = 1;</code>
     */
    public fun clearName() {
      _builder.clearName()
    }
    /**
     * <pre>
     * Имя игрока (для отображения в интерфейсе)
     * </pre>
     *
     * <code>required string name = 1;</code>
     * @return Whether the name field is set.
     */
    public fun hasName(): kotlin.Boolean {
      return _builder.hasName()
    }

    /**
     * <pre>
     * Уникальный идентификатор игрока в пределах игры
     * </pre>
     *
     * <code>required int32 id = 2;</code>
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <pre>
     * Уникальный идентификатор игрока в пределах игры
     * </pre>
     *
     * <code>required int32 id = 2;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }
    /**
     * <pre>
     * Уникальный идентификатор игрока в пределах игры
     * </pre>
     *
     * <code>required int32 id = 2;</code>
     * @return Whether the id field is set.
     */
    public fun hasId(): kotlin.Boolean {
      return _builder.hasId()
    }

    /**
     * <pre>
     * IPv4 или IPv6 адрес игрока в виде строки. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional string ip_address = 3;</code>
     */
    public var ipAddress: kotlin.String
      @JvmName("getIpAddress")
      get() = _builder.getIpAddress()
      @JvmName("setIpAddress")
      set(value) {
        _builder.setIpAddress(value)
      }
    /**
     * <pre>
     * IPv4 или IPv6 адрес игрока в виде строки. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional string ip_address = 3;</code>
     */
    public fun clearIpAddress() {
      _builder.clearIpAddress()
    }
    /**
     * <pre>
     * IPv4 или IPv6 адрес игрока в виде строки. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional string ip_address = 3;</code>
     * @return Whether the ipAddress field is set.
     */
    public fun hasIpAddress(): kotlin.Boolean {
      return _builder.hasIpAddress()
    }

    /**
     * <pre>
     * Порт UDP-сокета игрока. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional int32 port = 4;</code>
     */
    public var port: kotlin.Int
      @JvmName("getPort")
      get() = _builder.getPort()
      @JvmName("setPort")
      set(value) {
        _builder.setPort(value)
      }
    /**
     * <pre>
     * Порт UDP-сокета игрока. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional int32 port = 4;</code>
     */
    public fun clearPort() {
      _builder.clearPort()
    }
    /**
     * <pre>
     * Порт UDP-сокета игрока. Отсутствует в описании игрока-отправителя сообщения
     * </pre>
     *
     * <code>optional int32 port = 4;</code>
     * @return Whether the port field is set.
     */
    public fun hasPort(): kotlin.Boolean {
      return _builder.hasPort()
    }

    /**
     * <pre>
     * Роль узла в топологии
     * </pre>
     *
     * <code>required .snakes.NodeRole role = 5;</code>
     */
    public var role: me.ippolitov.fit.snakes.SnakesProto.NodeRole
      @JvmName("getRole")
      get() = _builder.getRole()
      @JvmName("setRole")
      set(value) {
        _builder.setRole(value)
      }
    /**
     * <pre>
     * Роль узла в топологии
     * </pre>
     *
     * <code>required .snakes.NodeRole role = 5;</code>
     */
    public fun clearRole() {
      _builder.clearRole()
    }
    /**
     * <pre>
     * Роль узла в топологии
     * </pre>
     *
     * <code>required .snakes.NodeRole role = 5;</code>
     * @return Whether the role field is set.
     */
    public fun hasRole(): kotlin.Boolean {
      return _builder.hasRole()
    }

    /**
     * <pre>
     * Тип игрока
     * </pre>
     *
     * <code>optional .snakes.PlayerType type = 6 [default = HUMAN];</code>
     */
    public var type: me.ippolitov.fit.snakes.SnakesProto.PlayerType
      @JvmName("getType")
      get() = _builder.getType()
      @JvmName("setType")
      set(value) {
        _builder.setType(value)
      }
    /**
     * <pre>
     * Тип игрока
     * </pre>
     *
     * <code>optional .snakes.PlayerType type = 6 [default = HUMAN];</code>
     */
    public fun clearType() {
      _builder.clearType()
    }
    /**
     * <pre>
     * Тип игрока
     * </pre>
     *
     * <code>optional .snakes.PlayerType type = 6 [default = HUMAN];</code>
     * @return Whether the type field is set.
     */
    public fun hasType(): kotlin.Boolean {
      return _builder.hasType()
    }

    /**
     * <pre>
     * Число очков, которые набрал игрок
     * </pre>
     *
     * <code>required int32 score = 7;</code>
     */
    public var score: kotlin.Int
      @JvmName("getScore")
      get() = _builder.getScore()
      @JvmName("setScore")
      set(value) {
        _builder.setScore(value)
      }
    /**
     * <pre>
     * Число очков, которые набрал игрок
     * </pre>
     *
     * <code>required int32 score = 7;</code>
     */
    public fun clearScore() {
      _builder.clearScore()
    }
    /**
     * <pre>
     * Число очков, которые набрал игрок
     * </pre>
     *
     * <code>required int32 score = 7;</code>
     * @return Whether the score field is set.
     */
    public fun hasScore(): kotlin.Boolean {
      return _builder.hasScore()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun me.ippolitov.fit.snakes.SnakesProto.GamePlayer.copy(block: me.ippolitov.fit.snakes.GamePlayerKt.Dsl.() -> kotlin.Unit): me.ippolitov.fit.snakes.SnakesProto.GamePlayer =
  me.ippolitov.fit.snakes.GamePlayerKt.Dsl._create(this.toBuilder()).apply { block() }._build()

